---
- name: Deploy full infrastructure using Docker
  hosts: all
  become: yes

  tasks:

    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present

    - name: Ensure Docker Compose is installed
      package:
        name: docker-compose
        state: present

    - name: Create kafka-data directory
      file:
        path: "{{ playbook_dir }}/kafka-data"
        state: directory
        mode: '0755'

    - name: Start Docker Compose
      shell: docker-compose up -d
      args:
        chdir: "{{ playbook_dir }}"
