version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /home/tagspo/web-infra/nginx.conf:/etc/nginx/nginx.conf
      - /home/tagspo/web-infra/html:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - /home/tagspo/web-infra/html:/var/www/html